Repository fluxcd/kustomize-controller, pull requests merged in 2020-12, with the labels that each got.

#194 Implement container image setters
  .github/workflows/e2e.yaml
  api/v1beta1/kustomization_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/testdata/overrides/test.yaml
  controllers/kustomization_generator.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
Labels: area/kustomize, enhancement

#195 Upgrade dependencies
  Makefile
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  controllers/kustomization_healthcheck.go
  go.mod
  go.sum
Labels: area/build

#198 Update kustomize/api to v0.7.0
  go.mod
  go.sum
Labels: area/build, area/kustomize

#200 Fix changelog PR links
  CHANGELOG.md
Labels: area/docs

#211 Make Path field optional and add safe guards for relative paths
  api/v1beta1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
  docs/spec/v1beta1/kustomization.md
  go.mod
  go.sum
Labels: enhancement

#210 Refactor garbage collection
  config/manager/deployment.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_gc.go
  go.mod
  go.sum
Labels: enhancement

#219 Emit healthcheck event when Kustomization was not ready
  controllers/kustomization_controller.go
Labels: area/health-checks

#218 Add debug logs to garbage collection
  controllers/kustomization_gc.go
Labels: area/kustomize
