Repository fluxcd/kustomize-controller, pull requests merged in 2020-10, with the labels that each got.

#131 Set default namespace to gotk-system
  Makefile
  README.md
  docs/spec/README.md
  docs/spec/v1beta1/kustomization.md
Labels: area/docs

#133 Set default branch to main
  .github/workflows/e2e.yaml
  .github/workflows/fossa.yml
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  docs/internal/release.md
Labels: area/build

#137 Update kustomize/api to v0.6.3
  README.md
  go.mod
  go.sum
Labels: area/kustomize

#138 Implement Prometheus instrumentation
  api/go.mod
  api/go.sum
  controllers/kustomization_controller.go
  go.mod
  go.sum
  main.go
Labels: area/kustomize, enhancement

#139 Add namespace to API docs examples
  docs/spec/v1beta1/kustomization.md
Labels: area/docs

#141 Fix status reporting when the source is not found
  Makefile
  config/default/kustomization.yaml
  controllers/kustomization_controller.go
Labels: area/kustomize, bug

#143 Validate manifests when generating kustomization.yaml
  controllers/kustomization_generator.go
Labels: area/kustomize

#146 Update remote cluster docs
  .github/workflows/fossa.yml
  .github/workflows/rebase.yml
  api/v1beta1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
Labels: area/docs

#148 Improve remote cluster documentation
  api/v1beta1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
Labels: area/docs

#153 Move dedicated watchers to in-controller watches
  config/rbac/role.yaml
  controllers/bucket_watcher.go
  controllers/gitrepository_watcher.go
  controllers/kustomization_controller.go
  main.go
Labels: enhancement
