Repository fluxcd/kustomize-controller, pull requests merged in 2020-09, with the labels that each got.

#95 Implement Mozilla SOPS decryption
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/kustomization_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/testdata/sops/keys.yaml
  config/testdata/sops/ks.yaml
  config/testdata/sops/kustomization.yaml
  config/testdata/sops/source.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor.go
  controllers/kustomization_gc.go
  controllers/kustomization_generator.go
  controllers/suite_test.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
  internal/sops/LICENSE
  internal/sops/keyservice/client.go
  internal/sops/keyservice/server.go
  internal/sops/pgp/keysource.go
Labels: area/kustomize, enhancement

#96 Publish amd64/arm64 images to GHCR
  .github/workflows/release.yml
  Dockerfile
Labels: area/build

#99 Fix GC snapshot
  controllers/kustomization_controller.go
Labels: bug

#102 Configure manager logging and set level to info
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#104 Refactor garbage collector
  api/v1alpha1/snapshot_types.go
  controllers/kustomization_controller.go
  controllers/kustomization_gc.go
Labels: area/kustomize, enhancement

#106 Add watch all namespaces flag
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#108 Update health assessment docs
  api/v1alpha1/reference_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_healthcheck.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
  main.go
Labels: area/docs, area/kustomize

#110 Set kubectl cache dir to /tmp
  controllers/kustomization_controller.go
Labels: enhancement

#111 Support dependency references to other namespaces
  README.md
  api/go.mod
  api/go.sum
  api/v1alpha1/kustomization_types.go
  api/v1alpha1/sort.go
  api/v1alpha1/sort_test.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/testdata/dependencies/backend.yaml
  config/testdata/dependencies/frontend.yaml
  controllers/gitrepository_watcher.go
  controllers/kustomization_controller.go
  docs/api/kustomize.md
  docs/spec/README.md
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
  hack/api-docs/config.json
Labels: enhancement

#112 Use manifests checksum in GC snapshot
  Makefile
  api/v1alpha1/snapshot_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_gc.go
  controllers/kustomization_generator.go
  docs/api/kustomize.md
Labels: area/kustomize, enhancement

#114 Normalize the ready condition reasons
  README.md
  api/v1alpha1/condition_types.go
  api/v1alpha1/kustomization_types.go
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  docs/internal/release.md
  docs/spec/README.md
  docs/spec/v1alpha1/README.md
  docs/spec/v1alpha1/kustomization.md
Labels: area/docs, area/kustomize, enhancement

#115 ci: Add sanity check for container images
  .github/workflows/release.yml
Labels: area/build

#117 Add support for S3 bucket sources
  .gitignore
  Makefile
  README.md
  api/v1alpha1/kustomization_types.go
  api/v1alpha1/reference_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/default/kustomization.yaml
  config/rbac/role.yaml
  controllers/bucket_predicate.go
  controllers/bucket_watcher.go
  controllers/kustomization_controller.go
  docs/diagrams/kustomize-controller-overview.png
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
  main.go
Labels: area/docs, area/kustomize, enhancement

#119 Publish ARM v7/v8 multi-arch image to GHCR
  .github/workflows/release.yml
  Dockerfile
Labels: area/build

#123 Implement namespace overriding
  api/v1alpha1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_generator.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
Labels: area/kustomize, enhancement

#124 Record last handled reconcile at annotation
  api/v1alpha1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
Labels: enhancement

#126 Implement reconciliation for remote clusters provisioned with CAPI
  api/v1alpha1/kustomization_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
Labels: enhancement
