Repository fluxcd/kustomize-controller, pull requests merged in 2020-07, with the labels that each got.

#57 Add last attempted revision to status
  api/v1alpha1/kustomization_types.go
  config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml
  controllers/gitrepository_watcher.go
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
Labels: area/docs, area/kustomize

#58 Setup production logging
  config/manager/deployment.yaml
  go.mod
  main.go
Labels: enhancement

#60 Rename syncAt annotation to reconcileAt
  Makefile
  README.md
  api/v1alpha1/kustomization_types.go
  config/default/kustomization.yaml
  controllers/gitrepository_watcher.go
  controllers/kustomization_controller.go
  controllers/kustomization_predicate.go
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
  main.go
Labels: enhancement

#63 Use Docker organization secrets in build
  .github/workflows/release.yml
Labels: area/build

#64 Improve error handling and reporting
  controllers/kustomization_controller.go
Labels: enhancement

#66 Implement cross-namespace source references
  Dockerfile
  api/v1alpha1/kustomization_types.go
  api/v1alpha1/reference_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml
  controllers/gitrepository_watcher.go
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
Labels: area/docs, area/git, enhancement

#69 Refactor garbage collector to finalizer
  api/v1alpha1/kustomization_types.go
  controllers/kustomization_controller.go
  controllers/kustomization_predicate.go
Labels: enhancement

#70 Upgrade CRDs to apiextensions.k8s.io/v1
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml
  config/default/kustomization.yaml
  config/testdata/dependencies/backend.yaml
  config/testdata/dependencies/common.yaml
  config/testdata/dependencies/frontend.yaml
  docs/spec/README.md
  go.mod
  go.sum
Labels: enhancement

#72 Take observed generation of dependencies into account
  api/v1alpha1/kustomization_types.go
  config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  docs/api/kustomize.md
  docs/spec/v1alpha1/kustomization.md
Labels: enhancement

#73 Remove local actions and use those from pkg
  .github/actions/kubebuilder/Dockerfile
  .github/actions/kubebuilder/action.yml
  .github/actions/kubebuilder/entrypoint.sh
  .github/actions/kubectl/Dockerfile
  .github/actions/kubectl/action.yml
  .github/actions/kubectl/entrypoint.sh
  .github/actions/kustomize/Dockerfile
  .github/actions/kustomize/action.yml
  .github/actions/kustomize/entrypoint.sh
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
Labels: area/build

#76 Set event reason from ready status reason
  api/v1alpha1/condition_types.go
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  docs/spec/v1alpha1/kustomization.md
Labels: bug

#77 Change CRD domain to 'kustomize.toolkit.fluxcd.io'
  CHANGELOG.md
  Makefile
  PROJECT
  README.md
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/crd/kustomization.yaml
  config/default/kustomization.yaml
  config/rbac/kustomization_editor_role.yaml
  config/rbac/kustomization_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/kustomize_v1alpha1_kustomization.yaml
  config/samples/source_v1alpha1_gitrepository.yaml
  config/testdata/dependencies/backend.yaml
  config/testdata/dependencies/common.yaml
  config/testdata/dependencies/frontend.yaml
  config/testdata/dependencies/source.yaml
  config/testdata/overlays/production.yaml
  config/testdata/overlays/staging.yaml
  controllers/gitrepository_watcher.go
  controllers/kustomization_controller.go
  docs/api/kustomize.md
  docs/spec/README.md
  docs/spec/v1alpha1/README.md
  docs/spec/v1alpha1/kustomization.md
  go.mod
  go.sum
Labels: enhancement
