Repository fluxcd/kustomize-controller, pull requests merged in 2020-08, with the labels that each got.

#82 Make use of dedicated fluxcd/pkg/testserver module
  Makefile
  config/default/kustomization.yaml
  controllers/kustomization_controller_test.go
  go.mod
  go.sum
Labels: area/build

#83 Make the api package a dedicated module
  Dockerfile
  api/go.mod
  api/go.sum
  go.mod
Labels: area/build

#85 Make various targets work after api pkg change
  Makefile
Labels: bug

#92 Implement kustomize create and build
  Dockerfile
  controllers/kustomization_controller.go
  go.mod
  go.sum
Labels: area/kustomize, enhancement

#93 Fix GC ignore unknown resource kind
  controllers/kustomization_controller.go
Labels: area/kustomize, bug
