Repository fluxcd/kustomize-controller, pull requests merged in 2021-01, with the labels that each got.

#221 Upgrade controller-runtime to v0.7.0
  .github/workflows/e2e.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/kustomization_types.go
  config/manager/deployment.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/role.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_impersonation.go
  controllers/kustomization_indexers.go
  controllers/source_predicate.go
  controllers/suite_test.go
  controllers/utils.go
  go.mod
  go.sum
  main.go
Labels: area/build, enhancement, hold

#229 Update kustomize/api to v0.7.1
  go.mod
  go.sum
Labels: area/kustomize

#230 Publish as single multi-arch Docker image
  .github/workflows/release.yml
Labels: area/build

#231 Update source API and kubectl
  Dockerfile
  Makefile
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#234 Upgrade runtime package to v0.6.2
  Makefile
  api/go.mod
  api/go.sum
  controllers/kustomization_controller.go
  go.mod
  go.sum
Labels: area/build

#238 Look for all accepted Kustomization filenames
  controllers/kustomization_generator.go
Labels: area/kustomize, enhancement

#240 Update Kubernetes packages to v1.20.2
  Makefile
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#241 Update kustomize/api to v0.7.2 and disable kyaml
  Dockerfile
  controllers/kustomization_controller.go
  controllers/kustomization_generator.go
  go.mod
  go.sum
Labels: area/build, area/kustomize, bug

#247 Update fluxcd/pkg/runtime to v0.8.0
  api/go.mod
  api/go.sum
  api/v1beta1/kustomization_types.go
  api/v1beta1/reference_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_healthcheck.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
  go.mod
  go.sum
  main.go
Labels: area/build

#248 Update source-controller/api to v0.7.0
  Makefile
  api/go.mod
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#250 Allow failed reconciliations to be scheduled at a different interval
  api/v1beta1/kustomization_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
Labels: area/docs, area/kustomize, enhancement

#256 Fix reconciliation retry scheduler
  controllers/kustomization_controller.go
Labels: bug
