Repository fluxcd/kustomize-controller, pull requests merged in 2021-06, with the labels that each got.

#353 Support decrypting any file format in secret generator
  controllers/kustomization_controller_sops_test.go
  controllers/kustomization_decryptor.go
  controllers/testdata/sops/.sops.yaml
  controllers/testdata/sops/month/kustomization.yaml
  controllers/testdata/sops/month/month.yaml
Labels: area/sops

#361 Add nightly builds workflow
  .github/workflows/nightly.yml
Labels: area/build

#343 Upgrade controller to Kustomize v4
  .github/workflows/nightly.yml
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/default/kustomization.yaml
  controllers/kustomization_controller_test.go
  controllers/kustomization_generator.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: area/kustomize, enhancement

#362 Move the GC checksum from labels to annotations
  CONTRIBUTING.md
  controllers/kustomization_controller_gc_test.go
  controllers/kustomization_controller_test.go
  controllers/kustomization_gc.go
  controllers/kustomization_generator.go
Labels: area/kustomize, enhancement

#365 Document GC checksum annotation
  config/rbac/role.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_controller_gc_test.go
  controllers/kustomization_controller_test.go
  controllers/kustomization_gc.go
  docs/spec/v1beta1/kustomization.md
Labels: area/docs

#364 Add support for in-line generic patches to Flux Kustomization API
  api/go.mod
  api/go.sum
  api/v1beta1/kustomization_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller_patch_test.go
  controllers/kustomization_generator.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
  go.mod
  go.sum
Labels: area/kustomize, enhancement

#367 Add YAML anchors to breaking changes
  CHANGELOG.md
Labels: area/docs

#370 Add the generic patch field to the API spec docs
  api/v1beta1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
Labels: area/docs

#378 Fix CI: Override kubebuilder kubectl
  .github/workflows/e2e.yaml
Labels: area/build

#377 Test kustomization depend on for improve ut
  controllers/kustomization_controller_test.go
Labels: area/kustomize

#380 e2e: Update Kubernetes to v1.21.1
  .github/workflows/e2e.yaml
Labels: area/build

#381 Update kubectl to v1.21.1
  .github/workflows/e2e.yaml
  Dockerfile
  config/testdata/impersonation/test.yaml
Labels: area/build
