Repository fluxcd/kustomize-controller, pull requests merged in 2021-03, with the labels that each got.

#291 Validate the var names before substitution
  controllers/kustomization_controller_test.go
  controllers/kustomization_varsub.go
  docs/spec/v1beta1/kustomization.md
Labels: area/varsub, enhancement

#293 Do not override the artifact fetch timeout
  controllers/kustomization_controller.go
Labels: enhancement

#298 Update dependencies
  .github/workflows/fossa.yml
  .github/workflows/scan.yml
  Makefile
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#299 Expose suspended status as Prometheus metric
  api/go.mod
  api/go.sum
  controllers/kustomization_controller.go
  go.mod
  go.sum
Labels: enhancement

#303 Set leader election deadline to 30s
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  main.go
Labels: enhancement

#304 Update SOPS to v3.7.0
  go.mod
  go.sum
  internal/sops/keyservice/server.go
Labels: area/build
