Repository fluxcd/kustomize-controller, pull requests merged in 2021-02, with the labels that each got.

#262 Add Healthy status condition
  api/v1beta1/condition_types.go
  api/v1beta1/kustomization_types.go
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
Labels: area/health-checks, enhancement

#264 Support Strategic Merge and JSON 6902 patches
  .github/workflows/e2e.yaml
  api/go.mod
  api/go.sum
  api/v1beta1/kustomization_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/testdata/overrides/images.yaml
  config/testdata/overrides/patches.yaml
  controllers/kustomization_generator.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
  go.mod
  go.sum
  hack/api-docs/config.json
  hack/boilerplate.go.txt
Labels: area/kustomize, enhancement

#265 Add "toolkit" to the API reference in README
  README.md
Labels: area/docs

#266 Enable pprof endpoints on metrics server
  go.mod
  go.sum
  main.go
Labels: area/build

#267 Allow disabling of prune on certain resources
  controllers/kustomization_gc.go
  docs/spec/v1beta1/kustomization.md
Labels: enhancement

#253 [RFC] Add support for variable substitutions
  api/v1beta1/kustomization_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  controllers/kustomization_generator.go
  docs/api/kustomize.md
  docs/spec/v1beta1/README.md
  docs/spec/v1beta1/kustomization.md
  go.mod
  go.sum
Labels: enhancement

#269 Update kustomize/api to v0.7.4 (last version without kyaml)
  go.mod
  go.sum
Labels: area/build

#275 Implement var substitution from ConfigMaps and Secrets
  api/v1beta1/kustomization_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  controllers/kustomization_gc.go
  controllers/kustomization_generator.go
  controllers/kustomization_varsub.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
Labels: area/varsub

#280 Extracting validation error from apply dry run output
  controllers/kustomization_controller.go
  controllers/utils.go
  controllers/utils_test.go
Labels: enhancement

#271 Add support for recreating objects when immutable fields are updated
  .github/workflows/e2e.yaml
  Makefile
  api/go.mod
  api/go.sum
  api/v1beta1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_controller_test.go
  docs/api/kustomize.md
  docs/spec/v1beta1/kustomization.md
  go.mod
  go.sum
Labels: area/kustomize, enhancement

#283 Update kubectl to v1.20.4
  .github/workflows/e2e.yaml
  Dockerfile
Labels: area/build

#284 Refactor release workflow
  .github/workflows/release.yml
Labels: area/build

#285 Update dependencies
  Makefile
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#287 Update sigs.k8s.io/cli-utils to v0.22.2
  go.mod
  go.sum
Labels: area/health-checks, bug

#289 Retry with exponential backoff when fetching artifacts
  controllers/kustomization_controller.go
  go.mod
  main.go
Labels: enhancement
