Repository fluxcd/kustomize-controller, pull requests merged in 2021-11, with the labels that each got.

#480 Remove gopass dependency
  go.mod
  go.sum
  internal/sops/pgp/keysource.go
Labels: area/build

#483 Warn when secrets are not decrypted before apply
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor.go
Labels: enhancement, area/sops

#484 Allow disabling the reconciliation of in-cluster resources
  controllers/kustomization_controller.go
  controllers/kustomization_force_test.go
  controllers/kustomization_inventory_test.go
  controllers/kustomization_transformer_test.go
  docs/spec/v1beta2/kustomization.md
Labels: enhancement

#488 Update controller to kustomize v4.4.1
  go.mod
  go.sum
Labels: area/kustomize

#489 Verify artifacts integrity
  Makefile
  config/default/kustomization.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor_test.go
  controllers/kustomization_dependson_test.go
  controllers/kustomization_force_test.go
  controllers/kustomization_inventory_test.go
  controllers/kustomization_prune_test.go
  controllers/kustomization_transformer_test.go
  controllers/kustomization_varsub_test.go
  controllers/kustomization_wait_test.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: enhancement

#497 Update opencontainers/{image-spec, runc}
  go.mod
  go.sum
Labels: area/build

#498 Replace deprecated dependencies
  controllers/kustomization_controller.go
  controllers/kustomization_force_test.go
  controllers/kustomization_generator.go
  controllers/kustomization_impersonation.go
  controllers/kustomization_indexers.go
  controllers/kustomization_prune_test.go
  controllers/kustomization_transformer_test.go
  controllers/kustomization_varsub_test.go
  go.mod
  go.sum
  internal/sops/keyservice/server.go
  internal/sops/pgp/keysource.go
Labels: area/build

#499 Update source-controller/api to v0.19.0
  Makefile
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build
