Repository fluxcd/kustomize-controller, pull requests merged in 2022-11, with the labels that each got.

#759 Update `keyvault/azkeys` Azure SDK to v0.9.0
  go.mod
  go.sum
  internal/sops/azkv/config.go
  internal/sops/azkv/config_test.go
  internal/sops/azkv/keysource.go
  internal/sops/azkv/keysource_integration_test.go
Labels: area/sops

#760 build: Bump gpg to alpine's edge
  Dockerfile
Labels: area/build

#761 Don't override the reconcile error on status patching
  controllers/kustomization_controller.go
  controllers/kustomization_wait_test.go
Labels: bug

#765 Remove nsswitch.conf creation from Dockerfile
  Dockerfile
Labels: area/build

#763 Refactor: Generate manifests with `flux/pkg/kustomize`
  api/go.mod
  api/go.sum
  controllers/kustomization_controller.go
  go.mod
  go.sum
  internal/generator/build.go
  internal/generator/build_test.go
  internal/generator/generator.go
  internal/generator/generator_test.go
  internal/generator/testdata/different-filenames/Kustomization/Kustomization
  internal/generator/testdata/different-filenames/Kustomization/deployment.yaml
  internal/generator/testdata/different-filenames/yaml/deployment.yaml
  internal/generator/testdata/different-filenames/yaml/kustomization.yaml
  internal/generator/testdata/different-filenames/yml/deployment.yaml
  internal/generator/testdata/different-filenames/yml/kustomization.yml
  internal/generator/testdata/panic/kustomization.yaml
  internal/generator/testdata/panic/secret.age.yaml
  internal/generator/testdata/relbase/clusters/base/configmap.yaml
  internal/generator/testdata/relbase/clusters/base/kustomization.yaml
  internal/generator/testdata/relbase/clusters/patches.yaml
  internal/generator/testdata/relbase/clusters/staging/flux-system/kustomization.yaml
  internal/generator/testdata/relbase/clusters/staging/flux-system/secret.yaml
  internal/generator/testdata/remote/kustomization.yaml
  internal/generator/varsub.go
Labels: area/kustomize

#768 Update Source API to v0.32.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#771 build: Fix cifuzz tests and improve fuzz tests' reliability
  controllers/kustomization_fuzzer_test.go
  tests/fuzz/README.md
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/oss_fuzz_prebuild.sh
Labels: area/build
