Repository fluxcd/kustomize-controller, pull requests merged in 2022-03, with the labels that each got.

#581 Allow shared ownership of in-cluster objects applied with kubectl
  api/v1beta2/kustomization_types.go
  controllers/kustomization_controller.go
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
Labels: enhancement, area/server-side-apply

#582 fixup reference to kubeval
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#495 SOPS: add support for Azure Key Vault credentials using SecretRef
  controllers/kustomization_decryptor.go
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
  internal/sops/azkv/keysource.go
  internal/sops/azkv/keysource_test.go
  internal/sops/keyservice/server.go
  main.go
Labels: enhancement, area/sops

#584 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/sops/azkv/keysource.go
Labels: area/build

#585 Run tidy compat before Go test
  Makefile
  api/go.sum
  go.sum
Labels: area/build

#587 Add Azure Key Vault integration to changelog
  CHANGELOG.md
Labels: area/docs

#588 Add note on new source-controller v1beta2
  CHANGELOG.md
Labels: area/docs

#594 Update Kustomize to v4.5.3
  go.mod
  go.sum
Labels: area/kustomize, area/build

#596 Update source-controller API to v0.22.3
  Makefile
  go.mod
  go.sum
Labels: area/build

#597 sops/keyservice: properly fallback to default
  .github/workflows/e2e.yaml
  Makefile
  config/default/kustomization.yaml
  controllers/kustomization_decryptor.go
  internal/sops/keyservice/server.go
Labels: bug, area/sops

#599 docs: fix PR link in Changelog
  CHANGELOG.md
Labels: area/docs

#602 Align version of dependencies when Fuzzing
  tests/fuzz/oss_fuzz_build.sh
Labels: area/build

#603 Add recommended settings to API docs
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#604 sops/azkv: ensure compatibility with upstream
  .github/workflows/e2e.yaml
  Makefile
  internal/sops/azkv/keysource.go
  internal/sops/azkv/keysource_integration_test.go
Labels: area/sops
