Repository fluxcd/kustomize-controller, pull requests merged in 2022-04, with the labels that each got.

#609 docs/spec/v1beta2: fix recommended settings typo
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#593 Add kubeconfig flags
  .github/workflows/e2e.yaml
  DEVELOPMENT.md
  Makefile
  controllers/kustomization_controller.go
  controllers/kustomization_impersonation.go
  go.mod
  go.sum
  internal/sops/azkv/keysource_integration_test.go
  main.go
Labels: enhancement, area/server-side-apply

#608 Implement health check for Kubernetes jobs
  internal/statusreaders/job.go
  internal/statusreaders/job_test.go
  main.go
Labels: enhancement, area/health-checks

#607 sops: various improvements and tests
  controllers/kustomization_decryptor.go
  go.mod
  go.sum
  internal/sops/age/keysource.go
  internal/sops/age/keysource_test.go
  internal/sops/azkv/config.go
  internal/sops/azkv/config_test.go
  internal/sops/azkv/keysource.go
  internal/sops/azkv/keysource_integration_test.go
  internal/sops/azkv/keysource_test.go
  internal/sops/hcvault/keysource.go
  internal/sops/hcvault/keysource_test.go
  internal/sops/keyservice/options.go
  internal/sops/keyservice/server.go
  internal/sops/keyservice/server_test.go
  internal/sops/keyservice/utils_test.go
  internal/sops/pgp/keysource.go
  internal/sops/pgp/keysource_test.go
  internal/sops/pgp/testdata/private.gpg
  internal/sops/pgp/testdata/public.gpg
  tests/fuzz/age_fuzzer.go
Labels: area/sops

#610 update toolkit.fluxcd.io docs link
  CHANGELOG.md
Labels: area/docs

#619 controllers: improve decryptor and add tests
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor.go
  controllers/kustomization_decryptor_test.go
Labels: enhancement, area/sops

#620 controllers: use own Kustomize FS implementation
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor.go
  controllers/kustomization_generator.go
  go.mod
  go.sum
Labels: enhancement, area/kustomize

#621 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#623 Update dependencies
  Makefile
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#626 generator: ensure remote build dirs can be reached
  controllers/kustomization_controller.go
  controllers/kustomization_generator.go
  controllers/kustomization_generator_test.go
  controllers/testdata/remote/kustomization.yaml
  go.mod
  go.sum
Labels: bug, area/kustomize

#628 Update golang.org/x/crypto
  go.mod
  go.sum
Labels: area/build

#630 Ensure generated temp dir is absolute on all OSes
  controllers/kustomization_controller.go
  controllers/utils.go
Labels: area/build

#631 feat: flags to configure exponential backoff retry
  controllers/kustomization_controller.go
  main.go
Labels: enhancement

#632 Update source-controller to v0.24.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#636 Use Secret generator keys for SOPS format hint
  controllers/kustomization_decryptor.go
  controllers/kustomization_decryptor_test.go
  controllers/suite_test.go
Labels: enhancement, area/sops

#637 generator: recover from kustomize build panics
  controllers/kustomization_generator.go
  controllers/kustomization_generator_test.go
  controllers/testdata/panic/kustomization.yaml
  controllers/testdata/panic/secret.age.yaml
Labels: enhancement, area/kustomize

#615 Support defining a KubeConfig Secret data key
  api/go.mod
  api/go.sum
  api/v1beta2/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_acl_test.go
  controllers/kustomization_decryptor_test.go
  controllers/kustomization_dependson_test.go
  controllers/kustomization_force_test.go
  controllers/kustomization_impersonation.go
  controllers/kustomization_impersonation_test.go
  controllers/kustomization_inventory_test.go
  controllers/kustomization_prune_test.go
  controllers/kustomization_transformer_test.go
  controllers/kustomization_validation_test.go
  controllers/kustomization_varsub_test.go
  controllers/kustomization_wait_test.go
  docs/api/kustomize.md
  go.mod
  go.sum
  tests/fuzz/controllers_fuzzer.go
Labels: enhancement
