Repository fluxcd/kustomize-controller, pull requests merged in 2022-05, with the labels that each got.

#638 Disallow remote bases usage in Kustomize overlays
  controllers/kustomization_controller.go
  controllers/kustomization_generator.go
  controllers/kustomization_generator_test.go
  docs/spec/v1beta2/kustomization.md
  main.go
Labels: enhancement, area/kustomize

#645 spec: take note of KubeConfig.SecretRef.Key field
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#647 Update SOPS to v3.7.3
  config/default/kustomization.yaml
  controllers/kustomization_decryptor.go
  go.mod
  go.sum
  internal/sops/keyservice/client.go
Labels: area/build, area/sops

#641 Support AWS KMS credentials using decryption secretRef
  controllers/kustomization_decryptor.go
  controllers/kustomization_decryptor_test.go
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
  internal/sops/awskms/keysource.go
  internal/sops/awskms/keysource_test.go
  internal/sops/hcvault/keysource_test.go
  internal/sops/keyservice/options.go
  internal/sops/keyservice/server.go
  internal/sops/keyservice/server_test.go
  internal/sops/keyservice/utils_test.go
Labels: enhancement, area/sops

#655 Set digests in image override
  controllers/kustomization_generator.go
  controllers/kustomization_transformer_test.go
  controllers/testdata/patch/deployment.yaml
Labels: enhancement, area/kustomize

#657 generator: test secure build relative base dir
  controllers/kustomization_generator_test.go
  controllers/testdata/relbase/clusters/base/configmap.yaml
  controllers/testdata/relbase/clusters/base/kustomization.yaml
  controllers/testdata/relbase/clusters/patches.yaml
  controllers/testdata/relbase/clusters/staging/flux-system/kustomization.yaml
  controllers/testdata/relbase/clusters/staging/flux-system/secret.yaml
Labels: area/kustomize

#650 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#660 Update controller to kustomize v4.5.5
  go.mod
  go.sum
Labels: area/build

#635 Support GCP KMS credentials using decryption secretRef
  controllers/kustomization_decryptor.go
  controllers/kustomization_decryptor_test.go
  controllers/kustomization_generator.go
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
  internal/sops/gcpkms/keysource.go
  internal/sops/gcpkms/keysource_integration_test.go
  internal/sops/gcpkms/keysource_test.go
  internal/sops/gcpkms/mock_kms_server_test.go
  internal/sops/keyservice/options.go
  internal/sops/keyservice/server.go
  internal/sops/keyservice/server_test.go
  internal/sops/keyservice/utils_test.go
Labels: enhancement, area/sops

#661 Update Alpine to v3.16
  Dockerfile
  go.mod
  go.sum
  internal/sops/gcpkms/mock_kms_server_test.go
Labels: area/build

#665 Update go-yaml to v3.0.0
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
  .github/workflows/rebase.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#667 sops/awskms: Fix AWS KMS config creation
  internal/sops/awskms/keysource.go
  internal/sops/awskms/keysource_test.go
Labels: area/sops

#670 sops/awskms: fix compatibility tests with upstream sops
  go.mod
  internal/sops/awskms/keysource_test.go
Labels: area/build, area/sops
