Repository fluxcd/kustomize-controller, pull requests merged in 2022-09, with the labels that each got.

#720 Reconcile Kubernetes class type objects in a dedicated stage
  controllers/kustomization_controller.go
  controllers/kustomization_fetcher_test.go
Labels: area/server-side-apply

#721 SOPS: Update the AWS SDK for KMS
  go.mod
  go.sum
Labels: area/sops

#723 fuzz: Refactor Fuzzers based on Go native fuzzing
  Makefile
  controllers/kustomization_dependson_test.go
  controllers/kustomization_fuzzer_test.go
  go.mod
  go.sum
  internal/sops/age/keysource_test.go
  internal/sops/pgp/keysource_test.go
  tests/fuzz/age_fuzzer.go
  tests/fuzz/controllers_fuzzer.go
  tests/fuzz/go.mod
  tests/fuzz/native_go_run.sh
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/pgp_fuzzer.go
Labels: area/build

#726 Sort SOPS masterkeys so offline decrypt methods are tried first
  controllers/kustomization_decryptor.go
  internal/sops/keyservice/keyservice.go
Labels: enhancement, area/sops

#730 Fix health checking for global objects
  controllers/kustomization_controller.go
  controllers/kustomization_wait_test.go
Labels: area/server-side-apply

#733 Build with Go 1.19
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  Dockerfile
  Makefile
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/rbac/role.yaml
  controllers/kustomization_generator.go
  internal/sops/azkv/config.go
Labels: area/build

#735 Update dependencies
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build
