Repository fluxcd/kustomize-controller, pull requests merged in 2022-10, with the labels that each got.

#738 Support alternative kustomization file names
  controllers/kustomization_controller.go
  controllers/kustomization_generator.go
  controllers/kustomization_generator_test.go
  controllers/testdata/different-filenames/Kustomization/Kustomization
  controllers/testdata/different-filenames/Kustomization/deployment.yaml
  controllers/testdata/different-filenames/yaml/deployment.yaml
  controllers/testdata/different-filenames/yaml/kustomization.yaml
  controllers/testdata/different-filenames/yml/deployment.yaml
  controllers/testdata/different-filenames/yml/kustomization.yml
  go.mod
  go.sum
Labels: bug, area/kustomize

#745 Refactor: Adopt Flux runtime conditions and status standards
  api/v1beta1/kustomization_types.go
  api/v1beta2/condition_types.go
  api/v1beta2/kustomization_types.go
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor_test.go
  controllers/kustomization_force_test.go
  controllers/kustomization_impersonation_test.go
  controllers/kustomization_prune_test.go
  controllers/kustomization_wait_test.go
  controllers/suite_test.go
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
  internal/decryptor/decryptor.go
  internal/decryptor/decryptor_test.go
  internal/generator/generator.go
  internal/generator/generator_test.go
  internal/generator/varsub.go
  main.go
Labels: enhancement

#746 Refactor: Remove docs which overlap with Flux website
  README.md
  docs/spec/README.md
  docs/spec/v1beta2/README.md
  docs/spec/v1beta2/kustomization.md
Labels: area/docs
