Repository fluxcd/kustomize-controller, pull requests merged in 2022-07, with the labels that each got.

#692 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#694 build: Upgrade to Go 1.18
  .github/workflows/e2e.yaml
  DEVELOPMENT.md
  Dockerfile
  Makefile
  api/go.mod
  go.mod
  tests/fuzz/go.mod
Labels: area/build

#691 decryptor: recover from SOPS store panic
  controllers/kustomization_decryptor.go
Labels: area/sops

#700 Fix typo from pune to prune
  docs/spec/v1beta2/kustomization.md
Labels: area/docs
