Repository fluxcd/kustomize-controller, pull requests merged in 2022-02, with the labels that each got.

#559 Update controller to kustomize v4.5.1
  go.mod
  go.sum
Labels: area/kustomize

#562 Transfer ownership of the kubectl managed fields
  go.mod
  go.sum
Labels: area/server-side-apply

#564 Fix typo in API docs
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#566 Clarify spec.path in API docs
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#567 Update controller to kustomize v4.5.2
  go.mod
  go.sum
Labels: area/kustomize

#570 Tolerate absence of resources in post-build substitution
  api/v1beta2/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_varsub.go
  controllers/kustomization_varsub_test.go
  controllers/suite_test.go
  docs/api/kustomize.md
  docs/spec/v1beta2/kustomization.md
Labels: enhancement, area/varsub

#574 Update dependencies
  go.mod
  go.sum
Labels: area/build

#576 Convert `stringData` to `data` before applying Secrets
  api/go.mod
  api/go.sum
  controllers/kustomization_impersonation.go
  go.mod
  go.sum
  main.go
Labels: area/server-side-apply

#580 Use main go.mod for fuzz tests
  tests/fuzz/oss_fuzz_build.sh
Labels: area/build
