Repository fluxcd/kustomize-controller, pull requests merged in 2022-01, with the labels that each got.

#523 Fix typo in API spec docs
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#478 Update Go to v1.17 and controller-runtime to v0.11
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  config/default/kustomization.yaml
  controllers/kustomization_controller.go
  go.mod
  go.sum
Labels: area/build

#525 Restore runc and image-spec patches
  go.mod
  go.sum
Labels: area/build

#529 Use go install instead of go get in Makefile
  Makefile
Labels: area/build

#535 Use patch instead of update when adding finalizers
  controllers/kustomization_controller.go
Labels: enhancement

#537 Docs - Add var substitution operator escape syntax
  docs/spec/v1beta2/kustomization.md
Labels: area/docs

#536 Refactor Fuzz implementation
  .github/workflows/cifuzz.yaml
  .gitignore
  Makefile
  controllers/suite_test.go
  tests/fuzz/Dockerfile.builder
  tests/fuzz/README.md
  tests/fuzz/age_fuzzer.go
  tests/fuzz/controllers_fuzzer.go
  tests/fuzz/go.mod
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/oss_fuzz_run.sh
  tests/fuzz/pgp_fuzzer.go
Labels: area/build

#540 Update development documentation
  DEVELOPMENT.md
Labels: area/docs

#538 SOPS: Add support for HashiCorp Vault token-based authentication
  .github/workflows/e2e.yaml
  controllers/kustomization_decryptor.go
  controllers/kustomization_decryptor_test.go
  controllers/suite_test.go
  controllers/testdata/sops/secret.vault.yaml
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
  internal/sops/hcvault/keysource.go
  internal/sops/keyservice/server.go
Labels: enhancement, area/sops

#541 Publish SBOM and sign release artifacts
  .github/workflows/release.yml
  .goreleaser.yaml
  Dockerfile
Labels: enhancement, area/build

#543 Add Permissions to github Workflows
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
  .github/workflows/rebase.yml
  .github/workflows/scan.yml
Labels: area/build

#544 Fix preflight validation
  controllers/kustomization_controller.go
  controllers/kustomization_decryptor_test.go
  controllers/kustomization_validation_test.go
  controllers/testdata/invalid/overlay/deployment.yaml
  controllers/testdata/invalid/overlay/kustomization.yaml
  controllers/testdata/invalid/plain/deployment.yaml
  go.mod
  go.sum
Labels: area/kustomize

#549 Allow disabling cross-namespace references
  api/go.mod
  api/go.sum
  controllers/kustomization_acl_test.go
  controllers/kustomization_controller.go
  controllers/suite_test.go
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
  main.go
Labels: enhancement

#550 Allow setting a default service account for impersonation
  controllers/kustomization_controller.go
  controllers/kustomization_impersonation.go
  controllers/kustomization_impersonation_test.go
  docs/spec/v1beta2/kustomization.md
  main.go
Labels: enhancement

#527 Revoke kubectl managed fields ownership
  .github/workflows/e2e.yaml
  config/testdata/managed-fields/podinfo.yaml
  controllers/kustomization_controller.go
  go.mod
  go.sum
Labels: enhancement

#551 Update source-controller/api to v0.21.1
  Makefile
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#552 Ensure object are finalized under impersonation
  controllers/kustomization_controller.go
  controllers/kustomization_impersonation.go
  controllers/kustomization_impersonation_test.go
Labels: enhancement
