Repository fluxcd/kustomize-controller, pull requests merged in 2023-07, with the labels that each got.

#908 Update dependencies
  .github/workflows/e2e.yaml
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/ci, dependencies

#911 Rename `controllers` to `controller`
  internal/controller/kustomization_acl_test.go
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_decryptor_test.go
  internal/controller/kustomization_dependson_test.go
  internal/controller/kustomization_fetcher_test.go
  internal/controller/kustomization_force_test.go
  internal/controller/kustomization_fuzzer_test.go
  internal/controller/kustomization_impersonation_test.go
  internal/controller/kustomization_indexers.go
  internal/controller/kustomization_inventory_test.go
  internal/controller/kustomization_prune_test.go
  internal/controller/kustomization_transformer_test.go
  internal/controller/kustomization_validation_test.go
  internal/controller/kustomization_varsub_test.go
  internal/controller/kustomization_wait_test.go
  internal/controller/source_predicate.go
  internal/controller/suite_test.go
  internal/controller/utils.go
  main.go
Labels: backport:release/v1.0.x

#913 Run backport workflow as fluxcdbot
  .github/workflows/backport.yaml
Labels: area/ci

#915 ci: backport: `token` -> `github_token`
  .github/workflows/backport.yaml
Labels: area/ci

#917 ci: Group all GH action updates under the same PR
  .github/dependabot.yaml
Labels: area/ci

#920 Exclude skipped resources from apply events
  internal/controller/kustomization_controller.go
  internal/controller/utils.go
Labels: backport:release/v1.0.x

#930 Handle delete before adding finalizer
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_controller_test.go
Labels: enhancement

#932 Bump `fluxcd/pkg/ssa` to improve immutable error detection
  go.mod
  go.sum
Labels: area/server-side-apply
