Repository fluxcd/kustomize-controller, pull requests merged in 2023-12, with the labels that each got.

#977 Fix broken links in API docs
  docs/spec/v1/README.md
  docs/spec/v1alpha1/README.md
  docs/spec/v1beta1/README.md
  docs/spec/v1beta2/README.md
Labels: area/docs

#1023 build: update Alpine to 3.19
  Dockerfile
Labels: area/ci, dependencies

#1021 Update Kustomize to v5.3.0
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
  internal/controller/kustomization_controller.go
Labels: dependencies

#1027 Add `backport:release/v1.2.x` label
  .github/labels.yaml
Labels: area/ci

#1028 Log HTTP errors to provide faster feedback
  go.mod
  go.sum
  internal/controller/kustomization_controller.go
Labels: area/ux, backport:release/v1.2.x

#1031 Update runtime to v0.43.3
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.2.x
