Repository fluxcd/kustomize-controller, pull requests merged in 2023-11, with the labels that each got.

#1005 Tweak permissions on various created files
  go.mod
  go.sum
  internal/controller/kustomization_fuzzer_test.go
  internal/decryptor/decryptor.go
  internal/decryptor/decryptor_test.go
Labels: enhancement

#1012 Disable status poller cache by default
  internal/features/features.go
Labels: area/kstatus

#997 Cleanup pods when recreating Kubernetes Jobs
  go.mod
  go.sum
Labels: area/server-side-apply

#1014 Update controller to Kustomize v5.2.1
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_inventory_test.go
  internal/inventory/inventory.go
  internal/inventory/inventory_test.go
  internal/statusreaders/job.go
  internal/statusreaders/job_test.go
  main.go
Labels: dependencies

#1017 Support additional Field Managers in the disallow list
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_disallowed_managers_test.go
  internal/controller/suite_test.go
  main.go
Labels: enhancement, area/server-side-apply

#1016 Add test for Namespace custom resource
  internal/controller/kustomization_controller_test.go
  internal/controller/testdata/crds/crd.yaml
Labels: area/testing
