Repository fluxcd/kustomize-controller, pull requests merged in 2023-03, with the labels that each got.

#803 kstatus: allow disabling of caching cluster reader
  internal/features/features.go
  main.go
Labels: enhancement, area/health-checks

#806 Update Go to 1.20
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  Dockerfile
  Makefile
Labels: area/build

#807 Update dependencies
  api/go.mod
  api/go.sum
  controllers/kustomization_controller.go
  go.mod
  go.sum
  internal/inventory/inventory_test.go
Labels: area/build

#809 Use `logger.SetLogger` to also configure `klog`
  go.mod
  go.sum
  main.go
Labels: enhancement

#808 build: update release workflow
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: area/build

#811 Update source-controller to v0.36.0
  .goreleaser.yaml
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: area/build

#818 Verify Digest of Artifact
  controllers/kustomization_controller.go
  controllers/kustomization_fuzzer_test.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: enhancement

#817 Add common labels and annotations patching capabilities
  api/v1beta2/kustomization_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  controllers/kustomization_controller.go
  controllers/kustomization_transformer_test.go
  docs/api/kustomize.md
  docs/spec/v1beta2/kustomization.md
  go.mod
  go.sum
Labels: enhancement, area/kustomize

#821 Add reconciler sharding capability based on label selector
  api/go.mod
  api/go.sum
  api/v1beta1/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  go.mod
  go.sum
  internal/controllers/kustomization_transformer_test.go
  main.go
Labels: enhancement

#823 build: update `actions/setup-go` in workflows
  .github/dependabot.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scan.yml
Labels: area/build
