Repository fluxcd/kustomize-controller, pull requests merged in 2023-08, with the labels that each got.

#933 Enable fail-fast behavior for health checks
  internal/controller/kustomization_controller.go
  internal/features/features.go
  main.go
Labels: enhancement, area/kstatus

#940 controller: jitter requeue interval
  api/v1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/api/v1/kustomize.md
  docs/spec/v1/kustomizations.md
  internal/controller/kustomization_controller.go
  main.go
Labels: enhancement

#942 ci: enable security-and-quality CodeQL query
  .github/workflows/scan.yml
Labels: area/ci

#943 Add `IfNotPresent` and `Ignore` SSA policies
  api/v1/kustomization_types.go
  docs/spec/v1/kustomizations.md
  go.mod
  go.sum
  internal/controller/kustomization_controller.go
Labels: area/docs, enhancement, area/server-side-apply

#948 Add `--concurrent-ssa` flag
  go.mod
  go.sum
  internal/controller/kustomization_controller.go
  internal/controller/suite_test.go
  main.go
Labels: enhancement, area/server-side-apply

#952 Update Source API to v1.1.0
  config/default/kustomization.yaml
  go.mod
  go.sum
  internal/controller/kustomization_force_test.go
Labels: dependencies, area/testing

#947 sops: drop forked keyservices
  Makefile
  go.mod
  go.sum
  internal/decryptor/decryptor.go
  internal/decryptor/decryptor_test.go
  internal/sops/LICENSE
  internal/sops/age/keysource.go
  internal/sops/age/keysource_test.go
  internal/sops/awskms/credentials.go
  internal/sops/awskms/credentials_test.go
  internal/sops/awskms/keysource.go
  internal/sops/awskms/keysource_test.go
  internal/sops/azkv/config.go
  internal/sops/azkv/config_test.go
  internal/sops/azkv/credentials.go
  internal/sops/azkv/keysource.go
  internal/sops/azkv/keysource_integration_test.go
  internal/sops/azkv/keysource_test.go
  internal/sops/gcpkms/keysource.go
  internal/sops/gcpkms/keysource_integration_test.go
  internal/sops/gcpkms/keysource_test.go
  internal/sops/gcpkms/mock_kms_server_test.go
  internal/sops/hcvault/keysource.go
  internal/sops/hcvault/keysource_test.go
  internal/sops/keyservice/keyservice.go
  internal/sops/keyservice/options.go
  internal/sops/keyservice/server.go
  internal/sops/keyservice/server_test.go
  internal/sops/keyservice/testdata/private.gpg
  internal/sops/keyservice/testdata/public.gpg
  internal/sops/keyservice/utils_test.go
  internal/sops/pgp/keysource.go
  internal/sops/pgp/keysource_test.go
Labels: enhancement, area/sops
