Repository fluxcd/kustomize-controller, pull requests merged in 2023-10, with the labels that each got.

#980 fix: Retry when artifacts are available in storage
  internal/controller/kustomization_indexers.go
Labels: bug, backport:release/v1.1.x

#983 Update `fluxcd/pkg` dependencies
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.1.x

#995 sops: update to v3.8.1
  go.mod
  go.sum
  internal/sops/keyservice/server.go
Labels: area/sops, dependencies

#996 Update source-controller to v1.1.2
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies
