Repository fluxcd/kustomize-controller, pull requests merged in 2023-05, with the labels that each got.

#838 Fix SOPS azkv envCred
  internal/sops/azkv/keysource.go
Labels: bug, area/sops

#853 Update dependencies
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#861 docs: Clarify the Kustomize components relative paths requirement
  docs/spec/v1/kustomization.md
Labels: area/docs

#862 Update dependencies
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#869 Update controller-runtime to v0.15.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controllers/kustomization_controller.go
  internal/controllers/kustomization_fuzzer_test.go
  internal/controllers/suite_test.go
  internal/sops/azkv/keysource.go
  main.go
Labels: dependencies

#873 Update source-controller to v1.0.0-rc.4
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies
