Repository fluxcd/kustomize-controller, pull requests merged in 2024-09, with the labels that each got.

#1242 docs: Clarify `.spec.decryption.secretRef` usage
  docs/spec/v1/kustomizations.md
Labels: area/docs

#1243 Update controller-gen to v0.16.1
  Makefile
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
Labels: dependencies

#1249 Update flux deps and k8s deps to 1.31.1
  api/go.mod
  api/go.sum
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies

#1248 Allow cross-shard dependency check
  internal/controller/kustomization_controller.go
  internal/controller/suite_test.go
  main.go
Labels: area/kstatus

#1251 Update source-controller to v1.4.1
  config/default/kustomization.yaml
  go.mod
  go.sum
Labels: dependencies
