Repository fluxcd/kustomize-controller, pull requests merged in 2024-12, with the labels that each got.

#1301 Clarify precedence in Kustomization substituteFrom
  docs/spec/v1/kustomizations.md
Labels: area/docs

#1302 Update SOPS to v3.9.2
  go.mod
  go.sum
Labels: dependencies

#1304 Update Kustomize packages to v5.5.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1310 Update dependencies to Kubernetes 1.32.0 and Go 1.23.0
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1314 Allow control of finalization garbage collection with `.spec.deletionPolicy`
  api/v1/kustomization_types.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/api/v1/kustomize.md
  docs/spec/v1/kustomizations.md
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_deletion_policy_test.go
Labels: enhancement, area/api
