Repository fluxcd/kustomize-controller, pull requests merged in 2025-04, with the labels that each got.

#1413 docs: mention CEL macros when discussing health check expressions
  docs/spec/v1/kustomizations.md
Labels: area/docs

#1396 Skip emitting events for suspended Kustomizations
  internal/controller/kustomization_controller.go
Labels: enhancement

#1427 docs: Update link to envsubst lib
  docs/spec/v1/kustomizations.md
Labels: area/docs

#1429 Update controller-runtime to v0.20.4
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1435 Update to Kubernetes 1.33.0 and Go 1.24.0
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yml
  DEVELOPMENT.md
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/decryptor/decryptor.go
  tests/fuzz/Dockerfile.builder
Labels: dependencies

#1436 Fix performance regression due to using client without cache
  internal/controller/kustomization_controller.go
Labels: area/server-side-apply, backport:release/v1.5.x
