Repository fluxcd/kustomize-controller, pull requests merged in 2025-07, with the labels that each got.

#1478 Fix regression in STS endpoint for SOPS decryption with AWS KMS in US Gov partition
  internal/sops/awskms/region.go
  internal/sops/awskms/region_test.go
Labels: bug, backport:release/v1.6.x

#1476 [RFC-0010] Introduce workload identity auth for remote clusters
  api/go.mod
  api/go.sum
  api/v1/zz_generated.deepcopy.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/spec/v1/kustomizations.md
  go.mod
  go.sum
  internal/cache/operations.go
  internal/controller/kustomization_acl_test.go
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_controller_test.go
  internal/controller/kustomization_decryptor_test.go
  internal/controller/kustomization_deletion_policy_test.go
  internal/controller/kustomization_dependson_test.go
  internal/controller/kustomization_disallowed_managers_test.go
  internal/controller/kustomization_fetcher_test.go
  internal/controller/kustomization_force_test.go
  internal/controller/kustomization_fuzzer_test.go
  internal/controller/kustomization_impersonation_test.go
  internal/controller/kustomization_inventory_test.go
  internal/controller/kustomization_origin_revision_test.go
  internal/controller/kustomization_patch_delete_test.go
  internal/controller/kustomization_prune_test.go
  internal/controller/kustomization_transformer_test.go
  internal/controller/kustomization_validation_test.go
  internal/controller/kustomization_varsub_test.go
  internal/controller/kustomization_wait_test.go
  internal/sops/awskms/region.go
Labels: enhancement, area/security

#1488 [RFC-0010] Support all Azure clouds for remote clusters at the controller level
  go.mod
  go.sum
Labels: enhancement, area/security

#1491 Extend the readiness evaluation of dependencies with CEL expressions
  api/v1/kustomization_types.go
  api/v1/reference_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
  docs/api/v1/kustomize.md
  docs/spec/v1/kustomizations.md
  go.mod
  go.sum
  internal/controller/constants.go
  internal/controller/kustomization_controller.go
  internal/controller/kustomization_dependson_test.go
  internal/controller/kustomization_manager.go
  internal/features/features.go
  main.go
Labels: enhancement, area/kstatus, area/api
